/**
 * G1 fuzz: whole-engine parity test — 1000 random ShotData vs C# golden-vector-runner.
 *
 * Companion to fixed-math-overflow.test.ts (site-specific :401 proof). This test
 * provides the empirical whole-engine guarantee that JS Number arithmetic is bit-exact
 * with C# long arithmetic across all arithmetic sites, for 1000 deterministic random
 * scenarios covering: max-force, back/top-spin, two-ball, three-ball, rail-bounce,
 * diagonal angles, and pocket-aimed shots.
 *
 * Fixture generated by tools/golden-vector-runner/Program.cs with seed=42.
 * To regenerate: cd tools/golden-vector-runner && ~/.dotnet/dotnet run -c Release 2>/dev/null > ../../tests/fixtures/physics-fuzz-vectors.json
 *
 * Load-bearing invariant enforced here:
 *   MAX_FORCE=65000 → maxVelocityFP=382352 → worst intermediate ~2^56.3
 *   All covered by the 2^6 divisibility structural guarantee (see fixed-math.ts header).
 *   Any case exceeding this bound would surface as a mismatch in this test.
 */
import { readFileSync } from 'fs';
import { resolve } from 'path';
import { describe, it, expect } from 'vitest';
import { CmVector } from '../../physics/cm-vector';
import { CmSphereCollider, CmPlaneCollider, CmLineCollider } from '../../physics/colliders';
import type { CmMaterial } from '../../physics/colliders';
import { CmRigidbody, CmForceMode, CmKinematicTrigger } from '../../physics/cm-rigidbody';
import { CmSpace } from '../../physics/cm-space';
import type { CmSpaceCube } from '../../physics/cm-collision';
import { simulateToCompletion } from '../../physics/simulate';
import {
  BALL_MASS, BALL_RADIUS, TABLE_Y, BALL_Y,
  BALL_MATERIAL as BALL_MAT,
  CLOTH_MATERIAL as CLOTH_MAT,
  RAIL_MATERIAL as RAIL_MAT,
  POCKET_RADIUS, POCKET_POSITIONS,
  SPACE_SCALE_X, SPACE_SCALE_Y, SPACE_SCALE_Z,
  RAIL_LONG_X, RAIL_LONG_SCALE_X, RAIL_LONG_RADIUS,
  RAIL_BACK_X, RAIL_BACK_Z, RAIL_SHORT_SCALE_X, RAIL_SHORT_RADIUS,
  CORNER_A_X, CORNER_A_Z, CORNER_A_SCALE_X, CORNER_A_RADIUS,
  CORNER_B_X, CORNER_B_Z, CORNER_B_SCALE_X, CORNER_B_RADIUS,
  DIAG_UNIT, PLANE_SCALE_X, PLANE_RADIUS,
} from '../../physics/constants';

// ─── Types ────────────────────────────────────────────────────────────────────

interface BodyState {
  id: number;
  px: number; py: number; pz: number;
  vx: number; vy: number; vz: number;
  ax: number; ay: number; az: number;
  isActive: boolean;
  isKinematic: boolean;
  isOutOfCube: boolean;
  pocketId: number;
}

interface FuzzVector {
  id: string;
  description: string;
  input: {
    ballPositions: Array<{ id: number; x: number; y: number; z: number }>;
    impulse: { x: number; y: number; z: number };
    torque:  { x: number; y: number; z: number };
    hitPoint: { x: number; y: number; z: number };
  };
  output: BodyState[];
  simSteps: number;
}

// ─── Load fuzz fixture ────────────────────────────────────────────────────────

const fixtureFile = resolve(__dirname, '../../../tests/fixtures/physics-fuzz-vectors.json');
const ALL_VECTORS: FuzzVector[] = JSON.parse(readFileSync(fixtureFile, 'utf-8'));
const FUZZ_VECTORS = ALL_VECTORS.filter(v => v.id.startsWith('FUZZ-'));

// ─── Scene setup (constants from physics/constants.ts, mirrors Program.cs) ───

const SPACE_CUBE: CmSpaceCube = {
  position: CmVector.zero,
  scale: new CmVector(SPACE_SCALE_X, SPACE_SCALE_Y, SPACE_SCALE_Z),
};

// ─── Geometry builders (mirrors Program.cs helpers) ───────────────────────────

function makeBall(id: number, x: number, y: number, z: number): CmRigidbody {
  const col = new CmSphereCollider();
  col.id = id;
  col.position = new CmVector(x, y, z);
  col.right    = new CmVector(10000, 0, 0);
  col.up       = new CmVector(0, 10000, 0);
  col.forward  = new CmVector(0, 0, 10000);
  col.scale    = new CmVector(BALL_RADIUS, BALL_RADIUS, BALL_RADIUS);
  col.radius   = BALL_RADIUS;
  col.material = { ...BALL_MAT };
  const body = new CmRigidbody();
  body.id   = id;
  body.mass = BALL_MASS;
  body.collider = col;
  return body;
}

function makeLine(
  id: number, px: number, py: number, pz: number,
  rx: number, ry: number, rz: number,
  ux: number, uy: number, uz: number,
  fx: number, fy: number, fz: number,
  scaleX: number, radius: number, mat: CmMaterial,
): CmLineCollider {
  const c = new CmLineCollider();
  c.id       = id;
  c.position = new CmVector(px, py, pz);
  c.right    = new CmVector(rx, ry, rz);
  c.up       = new CmVector(ux, uy, uz);
  c.forward  = new CmVector(fx, fy, fz);
  c.scale    = new CmVector(scaleX, 5000, 5000);
  c.radius   = radius;
  c.material = { ...mat };
  return c;
}

function makeTable(): (CmPlaneCollider | CmLineCollider)[] {
  const list: (CmPlaneCollider | CmLineCollider)[] = [];
  let id = 0;
  const plane = new CmPlaneCollider();
  plane.id       = id++;
  plane.position = new CmVector(0, TABLE_Y, 0);
  plane.right    = new CmVector(10000, 0, 0);
  plane.up       = new CmVector(0, 10000, 0);
  plane.forward  = new CmVector(0, 0, 10000);
  plane.scale    = new CmVector(PLANE_SCALE_X, 5000, PLANE_RADIUS);
  plane.radius   = PLANE_RADIUS;
  plane.material = { ...CLOTH_MAT };
  list.push(plane);
  list.push(makeLine(id++,  RAIL_LONG_X, BALL_Y,     0,   0,0,10000,  0,10000,0, -10000,0,0,  RAIL_LONG_SCALE_X, RAIL_LONG_RADIUS, RAIL_MAT));
  list.push(makeLine(id++, -RAIL_LONG_X, BALL_Y,     0,   0,0,-10000, 0,10000,0,  10000,0,0,  RAIL_LONG_SCALE_X, RAIL_LONG_RADIUS, RAIL_MAT));
  list.push(makeLine(id++,  RAIL_BACK_X, BALL_Y,  RAIL_BACK_Z,  -10000,0,0,  0,10000,0,  0,0,-10000, RAIL_SHORT_SCALE_X, RAIL_SHORT_RADIUS, RAIL_MAT));
  list.push(makeLine(id++, -RAIL_BACK_X, BALL_Y, -RAIL_BACK_Z,   10000,0,0,  0,10000,0,  0,0, 10000, RAIL_SHORT_SCALE_X, RAIL_SHORT_RADIUS, RAIL_MAT));
  list.push(makeLine(id++,  CORNER_A_X, BALL_Y,  CORNER_A_Z,  -DIAG_UNIT,0,-DIAG_UNIT, 0,10000,0,  DIAG_UNIT,0,-DIAG_UNIT, CORNER_A_SCALE_X, CORNER_A_RADIUS, RAIL_MAT));
  list.push(makeLine(id++,  CORNER_B_X, BALL_Y,  CORNER_B_Z,   DIAG_UNIT,0, DIAG_UNIT, 0,10000,0, -DIAG_UNIT,0, DIAG_UNIT, CORNER_B_SCALE_X, CORNER_B_RADIUS, RAIL_MAT));
  list.push(makeLine(id++, -CORNER_A_X, BALL_Y, -CORNER_A_Z,   DIAG_UNIT,0, DIAG_UNIT, 0,10000,0, -DIAG_UNIT,0, DIAG_UNIT, CORNER_A_SCALE_X, CORNER_A_RADIUS, RAIL_MAT));
  list.push(makeLine(id++, -CORNER_B_X, BALL_Y, -CORNER_B_Z,  -DIAG_UNIT,0,-DIAG_UNIT, 0,10000,0,  DIAG_UNIT,0,-DIAG_UNIT, CORNER_B_SCALE_X, CORNER_B_RADIUS, RAIL_MAT));
  return list;
}

function makePockets(): CmKinematicTrigger[] {
  return POCKET_POSITIONS.map(([px, pz], i) => {
    const t = new CmKinematicTrigger();
    t.id       = i;
    t.position = new CmVector(px, BALL_Y, pz);
    t.radius   = POCKET_RADIUS;
    return t;
  });
}

// ─── Runner (mirrors C# RunShot) ─────────────────────────────────────────────

function runFuzz(fv: FuzzVector): BodyState[] {
  const colls   = makeTable();
  const pockets = makePockets();

  const bodies = fv.input.ballPositions.map(bp =>
    makeBall(bp.id, bp.x, bp.y, bp.z),
  );

  const space = new CmSpace();
  space.init(SPACE_CUBE, bodies, colls, pockets);

  const cueBall = bodies[0];
  const imp = new CmVector(fv.input.impulse.x, fv.input.impulse.y, fv.input.impulse.z);
  const hitPt = new CmVector(fv.input.hitPoint.x, fv.input.hitPoint.y, fv.input.hitPoint.z);
  cueBall.addImpulse(imp, hitPt, CmForceMode.Impulse);

  const torq = fv.input.torque;
  if (torq.x !== 0 || torq.y !== 0 || torq.z !== 0) {
    cueBall.addTorque(new CmVector(torq.x, torq.y, torq.z), CmForceMode.Impulse);
  }

  // Canonical loop — shared with golden-vector.test.ts and simulation-loop.ts (applyShot)
  simulateToCompletion(space);

  return bodies.map(b => ({
    id: b.id,
    px: b.collider.position.x,
    py: b.collider.position.y,
    pz: b.collider.position.z,
    vx: b.velocity.x,
    vy: b.velocity.y,
    vz: b.velocity.z,
    ax: b.angularVelocity.x,
    ay: b.angularVelocity.y,
    az: b.angularVelocity.z,
    isActive: b.isActive,
    isKinematic: b.isKinematic,
    isOutOfCube: b.isOutOfCube,
    pocketId: b.kinematicTriggerId,
  }));
}

// ─── Test: 1000-case whole-engine parity ─────────────────────────────────────

describe('G1 fuzz: whole-engine JS Number parity vs C# golden-vector-runner (1000 cases)', () => {
  it('fixture loaded: 1000 FUZZ cases present', () => {
    expect(FUZZ_VECTORS.length).toBe(1000);
  });

  it('all 1000 fuzz cases bit-exact with C# (final ball positions, states)', () => {
    let mismatches = 0;
    const failures: string[] = [];

    for (const fv of FUZZ_VECTORS) {
      const actual = runFuzz(fv);
      for (const expected of fv.output) {
        const got = actual.find(b => b.id === expected.id);
        if (!got) {
          mismatches++;
          failures.push(`${fv.id}: ball ${expected.id} missing`);
          continue;
        }
        const fields: (keyof BodyState)[] = ['px','py','pz','vx','vy','vz','ax','ay','az','isActive','isKinematic','isOutOfCube','pocketId'];
        for (const f of fields) {
          if (got[f] !== expected[f]) {
            mismatches++;
            failures.push(`${fv.id} ball${expected.id}.${f}: expected ${expected[f]}, got ${got[f]}`);
          }
        }
      }
    }

    if (failures.length > 0) {
      console.error(`[FUZZ FAIL] ${failures.length} mismatches:`);
      failures.slice(0, 20).forEach(f => console.error(' ', f));
    }

    expect(mismatches).toBe(0);
  });
});
