/**
 * P1-T01 Golden Vector Regression Tests.
 *
 * Loads fixtures from tests/fixtures/physics-golden-vectors.json (generated by
 * running the original C# CalculableMechanics engine via /tmp/pool-golden-vector/).
 *
 * Each test drives the TypeScript physics engine with the exact same inputs and
 * asserts bit-level identical final ball positions and state.
 *
 * Scene constants are taken directly from Assets/_Game/BallPool/BallPool8/Scenes/Game.unity.
 *
 * Iron laws (from web-developer-soul.md):
 *   ① fixed-point integer only — no JS floats in physics
 *   ② timestep decoupled from wall-clock
 *   ③ CmVector string hashKey as Map key
 */
import { readFileSync } from 'fs';
import { resolve } from 'path';
import { describe, it, expect } from 'vitest';
import { CmVector } from '../../physics/cm-vector';
import { CmSphereCollider, CmPlaneCollider, CmLineCollider } from '../../physics/colliders';
import type { CmMaterial } from '../../physics/colliders';
import { CmRigidbody, CmForceMode, CmKinematicTrigger } from '../../physics/cm-rigidbody';
import { CmSpace } from '../../physics/cm-space';
import type { CmSpaceCube } from '../../physics/cm-collision';

// ─── Types mirroring the JSON fixture schema ────────────────────────────────

interface BodyState {
  id: number;
  px: number; py: number; pz: number;
  vx: number; vy: number; vz: number;
  ax: number; ay: number; az: number;
  isActive: boolean;
  isKinematic: boolean;
  isOutOfCube: boolean;
  pocketId: number;
}

interface GoldenVector {
  id: string;
  description: string;
  input: {
    ballPositions: Array<{ id: number; x: number; y: number; z: number }>;
    impulse: { x: number; y: number; z: number };
    torque: { x: number; y: number; z: number };
    hitPoint: { x: number; y: number; z: number };
  };
  output: BodyState[];
  simSteps: number;
}

// ─── Load fixture ───────────────────────────────────────────────────────────

const fixtureFile = resolve(__dirname, '../../../tests/fixtures/physics-golden-vectors.json');
const GOLDEN_VECTORS: GoldenVector[] = JSON.parse(readFileSync(fixtureFile, 'utf-8'));

// ─── Scene constants (from Game.unity — do NOT change) ─────────────────────

const BALL_MASS   = 1700;
const BALL_RADIUS = 285;
const TABLE_Y     = 9154;
const BALL_Y      = 9440; // TABLE_Y + BALL_RADIUS (rounded as in scene)

// Ball-ball contact material
const BALL_MAT: CmMaterial  = { bounciness: 9499, rollingFriction: 49,  twistingFriction: 200000, dynamicFriction: 500,  staticFriction: 599  };
// Table cloth (plane)
const CLOTH_MAT: CmMaterial = { bounciness: 500,  rollingFriction: 99,  twistingFriction: 200000, dynamicFriction: 8000, staticFriction: 8999 };
// Cushion rail
const RAIL_MAT: CmMaterial  = { bounciness: 6000, rollingFriction: 0,   twistingFriction: 0,      dynamicFriction: 0,    staticFriction: 2000 };

// ─── Scene geometry helpers ─────────────────────────────────────────────────

function makeBall(id: number, x: number, y: number, z: number): CmRigidbody {
  const col = new CmSphereCollider();
  col.id = id;
  col.position = new CmVector(x, y, z);
  col.right   = new CmVector(10000, 0, 0);
  col.up      = new CmVector(0, 10000, 0);
  col.forward = new CmVector(0, 0, 10000);
  col.scale   = new CmVector(BALL_RADIUS, BALL_RADIUS, BALL_RADIUS);
  col.radius  = BALL_RADIUS;
  col.material = { ...BALL_MAT };
  const body = new CmRigidbody();
  body.id   = id;
  body.mass = BALL_MASS;
  body.collider = col;
  return body;
}

function makeLine(
  id: number,
  px: number, py: number, pz: number,
  rx: number, ry: number, rz: number,
  ux: number, uy: number, uz: number,
  fx: number, fy: number, fz: number,
  scaleX: number, radius: number,
  mat: CmMaterial,
): CmLineCollider {
  const c = new CmLineCollider();
  c.id       = id;
  c.position = new CmVector(px, py, pz);
  c.right    = new CmVector(rx, ry, rz);
  c.up       = new CmVector(ux, uy, uz);
  c.forward  = new CmVector(fx, fy, fz);
  c.scale    = new CmVector(scaleX, 5000, 5000);
  c.radius   = radius;
  c.material = { ...mat };
  return c;
}

/** Build table geometry (plane + long/short rails) from Game.unity values */
function makeTable(): (CmPlaneCollider | CmLineCollider)[] {
  const list: (CmPlaneCollider | CmLineCollider)[] = [];
  let id = 0;

  // Table plane
  const plane = new CmPlaneCollider();
  plane.id       = id++;
  plane.position = new CmVector(0, TABLE_Y, 0);
  plane.right    = new CmVector(10000, 0, 0);
  plane.up       = new CmVector(0, 10000, 0);
  plane.forward  = new CmVector(0, 0, 10000);
  plane.scale    = new CmVector(25399, 5000, 12699);
  plane.radius   = 12699;
  plane.material = { ...CLOTH_MAT };
  list.push(plane);

  // Right long rail  x=+12699  (right=(0,0,+1))
  list.push(makeLine(id++,  12699, BALL_Y,     0,   0,0,10000, 0,10000,0, -10000,0,0,   11150, 5575, RAIL_MAT));
  // Left long rail   x=-12699  (right=(0,0,-1))
  list.push(makeLine(id++, -12699, BALL_Y,     0,   0,0,-10000, 0,10000,0, 10000,0,0,   11150, 5575, RAIL_MAT));
  // Back short rail  z=+6349   (right=(-1,0,0))
  list.push(makeLine(id++,   6290, BALL_Y,  6349,  -10000,0,0, 0,10000,0, 0,0,-10000,   11269, 5634, RAIL_MAT));
  // Front short rail z=-6349   (right=(+1,0,0))
  list.push(makeLine(id++,  -6290, BALL_Y, -6349,   10000,0,0, 0,10000,0, 0,0, 10000,   11269, 5634, RAIL_MAT));

  // Corner pocket cushion guards (angled)
  list.push(makeLine(id++,   12128, BALL_Y,  6552,  -7071,0,-7071, 0,10000,0,  7071,0,-7071,  570, 285, RAIL_MAT));
  list.push(makeLine(id++,   12901, BALL_Y,  5778,   7071,0, 7071, 0,10000,0, -7071,0, 7071,  569, 284, RAIL_MAT));
  list.push(makeLine(id++,  -12128, BALL_Y, -6552,   7071,0, 7071, 0,10000,0, -7071,0, 7071,  570, 285, RAIL_MAT));
  list.push(makeLine(id++,  -12901, BALL_Y, -5778,  -7071,0,-7071, 0,10000,0,  7071,0,-7071,  569, 284, RAIL_MAT));

  return list;
}

/** 6 pocket triggers from Game.unity */
function makePockets(): CmKinematicTrigger[] {
  const positions: [number, number, number][] = [
    [ 12875, BALL_Y,  6510], [ 12875, BALL_Y, -6510],
    [-12875, BALL_Y,  6510], [-12875, BALL_Y, -6510],
    [     0, BALL_Y,  7100], [     0, BALL_Y, -7100],
  ];
  return positions.map(([x, y, z], i) => {
    const t = new CmKinematicTrigger();
    t.id       = i;
    t.position = new CmVector(x, y, z);
    t.radius   = 450;
    return t;
  });
}

const SPACE_CUBE: CmSpaceCube = {
  position: CmVector.zero,
  scale: new CmVector(30000, 20000, 20000),
};

// ─── Helper: run simulation to completion (or max steps) ───────────────────

function simulate(space: CmSpace, maxSteps: number): number {
  let steps = 0;
  while (space.isActive && steps < maxSteps) {
    space.calculate(null, false);
    steps++;
  }
  return steps;
}

// ─── Golden Vector Tests ────────────────────────────────────────────────────

for (const gv of GOLDEN_VECTORS) {
  describe(`${gv.id}: ${gv.description}`, () => {
    it('final ball positions match C# golden output (bit-exact)', () => {
      // Build bodies from fixture input positions
      const bodies = gv.input.ballPositions.map(bp =>
        makeBall(bp.id, bp.x, bp.y, bp.z),
      );

      const colls   = makeTable();
      const pockets = makePockets();
      const space   = new CmSpace();
      space.init(SPACE_CUBE, bodies, colls, pockets);

      // Apply impulse to cue ball (body[0])
      const cueBall = bodies[0];
      const imp     = new CmVector(gv.input.impulse.x, gv.input.impulse.y, gv.input.impulse.z);
      const hitPt   = new CmVector(gv.input.hitPoint.x, gv.input.hitPoint.y, gv.input.hitPoint.z);
      cueBall.addImpulse(imp, hitPt, CmForceMode.Impulse);

      const torq = gv.input.torque;
      if (torq.x !== 0 || torq.y !== 0 || torq.z !== 0) {
        cueBall.addTorque(new CmVector(torq.x, torq.y, torq.z), CmForceMode.Impulse);
      }

      simulate(space, 2_000_000);

      // Assert each ball's final state against golden output
      for (const expected of gv.output) {
        const body = bodies.find(b => b.id === expected.id);
        expect(body).toBeDefined();
        if (!body) continue;

        const pos = body.collider.position;

        expect(pos.x).toBe(expected.px);
        expect(pos.y).toBe(expected.py);
        expect(pos.z).toBe(expected.pz);
        expect(body.velocity.x).toBe(expected.vx);
        expect(body.velocity.y).toBe(expected.vy);
        expect(body.velocity.z).toBe(expected.vz);
        // ax/ay/az intentionally not asserted: angular velocity is always 0 at rest (deactivated state)
        expect(body.isActive).toBe(expected.isActive);
        expect(body.isKinematic).toBe(expected.isKinematic);
        expect(body.isOutOfCube).toBe(expected.isOutOfCube);
        expect(body.kinematicTriggerId).toBe(expected.pocketId);
      }
    });
  });
}
