/**
 * P1-T01 Golden Vector Regression Tests.
 *
 * Loads fixtures from tests/fixtures/physics-golden-vectors.json (generated by
 * running the original C# CalculableMechanics engine via /tmp/pool-golden-vector/).
 *
 * Each test drives the TypeScript physics engine with the exact same inputs and
 * asserts bit-level identical final ball positions and state.
 *
 * Scene constants are taken directly from Assets/_Game/BallPool/BallPool8/Scenes/Game.unity.
 *
 * Iron laws (from web-developer-soul.md):
 *   ① fixed-point integer only — no JS floats in physics
 *   ② timestep decoupled from wall-clock
 *   ③ CmVector string hashKey as Map key
 */
import { readFileSync } from 'fs';
import { resolve } from 'path';
import { describe, it, expect } from 'vitest';
import { CmVector } from '../../physics/cm-vector';
import { CmSphereCollider, CmPlaneCollider, CmLineCollider } from '../../physics/colliders';
import type { CmMaterial } from '../../physics/colliders';
import { CmRigidbody, CmForceMode, CmKinematicTrigger } from '../../physics/cm-rigidbody';
import { CmSpace } from '../../physics/cm-space';
import type { CmSpaceCube } from '../../physics/cm-collision';
import { simulateToCompletion } from '../../physics/simulate';
import {
  BALL_MASS, BALL_RADIUS, TABLE_Y, BALL_Y,
  BALL_MATERIAL as BALL_MAT,
  CLOTH_MATERIAL as CLOTH_MAT,
  RAIL_MATERIAL as RAIL_MAT,
  POCKET_RADIUS, POCKET_POSITIONS,
  SPACE_SCALE_X, SPACE_SCALE_Y, SPACE_SCALE_Z,
  RAIL_LONG_X, RAIL_LONG_SCALE_X, RAIL_LONG_RADIUS,
  RAIL_BACK_X, RAIL_BACK_Z, RAIL_SHORT_SCALE_X, RAIL_SHORT_RADIUS,
  CORNER_A_X, CORNER_A_Z, CORNER_A_SCALE_X, CORNER_A_RADIUS,
  CORNER_B_X, CORNER_B_Z, CORNER_B_SCALE_X, CORNER_B_RADIUS,
  DIAG_UNIT, PLANE_SCALE_X, PLANE_RADIUS,
} from '../../physics/constants';

// ─── Types mirroring the JSON fixture schema ────────────────────────────────

interface BodyState {
  id: number;
  px: number; py: number; pz: number;
  vx: number; vy: number; vz: number;
  ax: number; ay: number; az: number;
  isActive: boolean;
  isKinematic: boolean;
  isOutOfCube: boolean;
  pocketId: number;
}

interface GoldenVector {
  id: string;
  description: string;
  input: {
    ballPositions: Array<{ id: number; x: number; y: number; z: number }>;
    impulse: { x: number; y: number; z: number };
    torque: { x: number; y: number; z: number };
    hitPoint: { x: number; y: number; z: number };
  };
  output: BodyState[];
  simSteps: number;
}

// ─── Load fixture ───────────────────────────────────────────────────────────

const fixtureFile = resolve(__dirname, '../../../tests/fixtures/physics-golden-vectors.json');
const ALL_VECTORS: GoldenVector[] = JSON.parse(readFileSync(fixtureFile, 'utf-8'));
// GV-NN prefix only — FUZZ-NNNN entries are covered by fuzz-parity.test.ts
const GOLDEN_VECTORS = ALL_VECTORS.filter(v => v.id.startsWith('GV-'));

// ─── Scene geometry helpers ─────────────────────────────────────────────────

function makeBall(id: number, x: number, y: number, z: number): CmRigidbody {
  const col = new CmSphereCollider();
  col.id = id;
  col.position = new CmVector(x, y, z);
  col.right   = new CmVector(10000, 0, 0);
  col.up      = new CmVector(0, 10000, 0);
  col.forward = new CmVector(0, 0, 10000);
  col.scale   = new CmVector(BALL_RADIUS, BALL_RADIUS, BALL_RADIUS);
  col.radius  = BALL_RADIUS;
  col.material = { ...BALL_MAT };
  const body = new CmRigidbody();
  body.id   = id;
  body.mass = BALL_MASS;
  body.collider = col;
  return body;
}

function makeLine(
  id: number,
  px: number, py: number, pz: number,
  rx: number, ry: number, rz: number,
  ux: number, uy: number, uz: number,
  fx: number, fy: number, fz: number,
  scaleX: number, radius: number,
  mat: CmMaterial,
): CmLineCollider {
  const c = new CmLineCollider();
  c.id       = id;
  c.position = new CmVector(px, py, pz);
  c.right    = new CmVector(rx, ry, rz);
  c.up       = new CmVector(ux, uy, uz);
  c.forward  = new CmVector(fx, fy, fz);
  c.scale    = new CmVector(scaleX, 5000, 5000);
  c.radius   = radius;
  c.material = { ...mat };
  return c;
}

/** Build table geometry (plane + long/short rails) from Game.unity values */
function makeTable(): (CmPlaneCollider | CmLineCollider)[] {
  const list: (CmPlaneCollider | CmLineCollider)[] = [];
  let id = 0;

  // Table plane
  const plane = new CmPlaneCollider();
  plane.id       = id++;
  plane.position = new CmVector(0, TABLE_Y, 0);
  plane.right    = new CmVector(10000, 0, 0);
  plane.up       = new CmVector(0, 10000, 0);
  plane.forward  = new CmVector(0, 0, 10000);
  plane.scale    = new CmVector(PLANE_SCALE_X, 5000, PLANE_RADIUS);
  plane.radius   = PLANE_RADIUS;
  plane.material = { ...CLOTH_MAT };
  list.push(plane);

  // Right long rail  x=+RAIL_LONG_X  (right=(0,0,+1))
  list.push(makeLine(id++,  RAIL_LONG_X, BALL_Y,     0,   0,0,10000, 0,10000,0, -10000,0,0,   RAIL_LONG_SCALE_X, RAIL_LONG_RADIUS, RAIL_MAT));
  // Left long rail   x=-RAIL_LONG_X  (right=(0,0,-1))
  list.push(makeLine(id++, -RAIL_LONG_X, BALL_Y,     0,   0,0,-10000, 0,10000,0, 10000,0,0,   RAIL_LONG_SCALE_X, RAIL_LONG_RADIUS, RAIL_MAT));
  // Back short rail  z=+RAIL_BACK_Z  (right=(-1,0,0))
  list.push(makeLine(id++,  RAIL_BACK_X, BALL_Y,  RAIL_BACK_Z,  -10000,0,0, 0,10000,0, 0,0,-10000,   RAIL_SHORT_SCALE_X, RAIL_SHORT_RADIUS, RAIL_MAT));
  // Front short rail z=-RAIL_BACK_Z  (right=(+1,0,0))
  list.push(makeLine(id++, -RAIL_BACK_X, BALL_Y, -RAIL_BACK_Z,   10000,0,0, 0,10000,0, 0,0, 10000,   RAIL_SHORT_SCALE_X, RAIL_SHORT_RADIUS, RAIL_MAT));

  // Corner pocket cushion guards (angled ±45°)
  list.push(makeLine(id++,  CORNER_A_X, BALL_Y,  CORNER_A_Z,  -DIAG_UNIT,0,-DIAG_UNIT, 0,10000,0,  DIAG_UNIT,0,-DIAG_UNIT, CORNER_A_SCALE_X, CORNER_A_RADIUS, RAIL_MAT));
  list.push(makeLine(id++,  CORNER_B_X, BALL_Y,  CORNER_B_Z,   DIAG_UNIT,0, DIAG_UNIT, 0,10000,0, -DIAG_UNIT,0, DIAG_UNIT, CORNER_B_SCALE_X, CORNER_B_RADIUS, RAIL_MAT));
  list.push(makeLine(id++, -CORNER_A_X, BALL_Y, -CORNER_A_Z,   DIAG_UNIT,0, DIAG_UNIT, 0,10000,0, -DIAG_UNIT,0, DIAG_UNIT, CORNER_A_SCALE_X, CORNER_A_RADIUS, RAIL_MAT));
  list.push(makeLine(id++, -CORNER_B_X, BALL_Y, -CORNER_B_Z,  -DIAG_UNIT,0,-DIAG_UNIT, 0,10000,0,  DIAG_UNIT,0,-DIAG_UNIT, CORNER_B_SCALE_X, CORNER_B_RADIUS, RAIL_MAT));

  return list;
}

function makePockets(): CmKinematicTrigger[] {
  return POCKET_POSITIONS.map(([px, pz], i) => {
    const t = new CmKinematicTrigger();
    t.id       = i;
    t.position = new CmVector(px, BALL_Y, pz);
    t.radius   = POCKET_RADIUS;
    return t;
  });
}

const SPACE_CUBE: CmSpaceCube = {
  position: CmVector.zero,
  scale: new CmVector(SPACE_SCALE_X, SPACE_SCALE_Y, SPACE_SCALE_Z),
};

// simulateToCompletion() imported from src/physics/simulate.ts — shared with
// fuzz-parity.test.ts and simulation-loop.ts (applyShot).  "Production path ==
// golden path" is a code-level guarantee, not an assertion.

// ─── Golden Vector Tests ────────────────────────────────────────────────────

for (const gv of GOLDEN_VECTORS) {
  describe(`${gv.id}: ${gv.description}`, () => {
    it('final ball positions match C# golden output (bit-exact)', () => {
      // Build bodies from fixture input positions
      const bodies = gv.input.ballPositions.map(bp =>
        makeBall(bp.id, bp.x, bp.y, bp.z),
      );

      const colls   = makeTable();
      const pockets = makePockets();
      const space   = new CmSpace();
      space.init(SPACE_CUBE, bodies, colls, pockets);

      // Apply impulse to cue ball (body[0])
      const cueBall = bodies[0];
      const imp     = new CmVector(gv.input.impulse.x, gv.input.impulse.y, gv.input.impulse.z);
      const hitPt   = new CmVector(gv.input.hitPoint.x, gv.input.hitPoint.y, gv.input.hitPoint.z);
      cueBall.addImpulse(imp, hitPt, CmForceMode.Impulse);

      const torq = gv.input.torque;
      if (torq.x !== 0 || torq.y !== 0 || torq.z !== 0) {
        cueBall.addTorque(new CmVector(torq.x, torq.y, torq.z), CmForceMode.Impulse);
      }

      simulateToCompletion(space);

      // Assert each ball's final state against golden output
      for (const expected of gv.output) {
        const body = bodies.find(b => b.id === expected.id);
        expect(body).toBeDefined();
        if (!body) continue;

        const pos = body.collider.position;

        expect(pos.x).toBe(expected.px);
        expect(pos.y).toBe(expected.py);
        expect(pos.z).toBe(expected.pz);
        expect(body.velocity.x).toBe(expected.vx);
        expect(body.velocity.y).toBe(expected.vy);
        expect(body.velocity.z).toBe(expected.vz);
        // PHY-017: angular velocity at rest must be 0 (isActive=false setter zeroes angularVelocity).
        // Non-zero ax/ay/az during flight is verified by GV-07/GV-09 final-position parity
        // (the spin phase drives a different trajectory, so any spin error shows up in px/pz).
        expect(body.angularVelocity.x).toBe(expected.ax);
        expect(body.angularVelocity.y).toBe(expected.ay);
        expect(body.angularVelocity.z).toBe(expected.az);
        expect(body.isActive).toBe(expected.isActive);
        expect(body.isKinematic).toBe(expected.isKinematic);
        expect(body.isOutOfCube).toBe(expected.isOutOfCube);
        expect(body.kinematicTriggerId).toBe(expected.pocketId);
      }
    });
  });
}
